name: Prettier Code Format Check

on: [pull_request]

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21" # Use whatever node version your project requires
      - name: Install Prettier
        run: npm install --save-dev prettier
      - name: Check code formatting
        run: npx prettier --check .
