name: Prettier Code Format Check

on: [pull_request]

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21" # Use whatever node version your project requires
      - name: Install Prettier
        run: yarn add prettier --dev
      - name: Check code formatting
        run: yarn pretty:check
        #run eslint
      - name: Install eslint
        run: yarn add eslint --dev
          yarn add eslint-config-prettier --dev
          yarn add eslint-plugin-prettier --dev
          yarn add eslint-plugin-react --dev
          yarn add eslint-plugin-react-hooks --dev
      - name: Check code formatting
        run: yarn eslint .
